import type {
  NextApiRequest,
  NextApiResponse,
} from "next";

import {
  generateVideoSasUrl,
} from "../../../../lib/azure/sas";

import {
  getVideosContainer,
} from "../../../../lib/azure/cosmos";

type VideoEntity = {
  id: string;

  videoId?: string;

  creatorId?: string;
  creatorName?: string;

  blobName?: string;
  convertedBlobName?: string;

  status?: string;

  title?: string;
};

type ResponseData = {
  success: boolean;
  videoUrl?: string;
  error?: string;
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseData>
) {
  if (req.method !== "GET") {
    return res.status(405).json({
      success: false,
      error: "Method not allowed.",
    });
  }

  const { videoId } = req.query;

  if (
    typeof videoId !== "string" ||
    !videoId.trim()
  ) {
    return res.status(400).json({
      success: false,
      error: "Invalid video ID.",
    });
  }

  try {
    console.log(
      `Generating SAS URL for video: ${videoId}`
    );

    const container =
      getVideosContainer();

    /*
     * Video metadata is stored in Cosmos DB.
     *
     * The Videos container is partitioned by
     * creatorId, so the video is located using
     * a cross-partition query because this public
     * playback route does not require authentication
     * and therefore does not know the creator ID.
     */
    const {
      resources,
    } = await container.items
      .query<VideoEntity>({
        query:
          "SELECT TOP 1 * FROM c WHERE c.videoId = @videoId",
        parameters: [
          {
            name: "@videoId",
            value: videoId,
          },
        ],
      })
      .fetchAll();

    const video = resources[0];

    if (!video) {
      console.error(
        `Video ${videoId} was not found in Cosmos DB`
      );

      return res.status(404).json({
        success: false,
        error:
          "Video record or storage resource was not found.",
      });
    }

    console.log(
      "Video entity found:",
      {
        videoId: video.videoId,
        blobName: video.blobName,
        convertedBlobName:
          video.convertedBlobName,
        status: video.status,
      }
    );

    /*
     * Prefer the converted MP4 when processing
     * has completed.
     *
     * The converted video is generated by the
     * Azure Function using FFmpeg.
     */
    let playbackBlobName:
      | string
      | undefined;

    if (
      video.status === "PROCESSED" &&
      video.convertedBlobName
    ) {
      playbackBlobName =
        video.convertedBlobName;
    } else if (video.blobName) {
      playbackBlobName =
        video.blobName;
    }

    if (!playbackBlobName) {
      console.error(
        `No blob name found for video ${videoId}`
      );

      return res.status(404).json({
        success: false,
        error:
          "Video file was not found.",
      });
    }

    console.log(
      `Generating SAS for blob: ${playbackBlobName}`
    );

    const videoUrl =
      generateVideoSasUrl(
        playbackBlobName
      );

    if (!videoUrl) {
      console.error(
        `Failed to generate SAS URL for blob: ${playbackBlobName}`
      );

      return res.status(500).json({
        success: false,
        error:
          "Failed to generate secure video URL.",
      });
    }

    console.log(
      `SAS URL generated successfully for video: ${videoId}`
    );

    return res.status(200).json({
      success: true,
      videoUrl,
    });
  } catch (error: any) {
    console.error(
      "Video SAS URL error:",
      error
    );

    if (
      error?.code === "NotFound" ||
      error?.code === "ResourceNotFound" ||
      error?.statusCode === 404
    ) {
      return res.status(404).json({
        success: false,
        error:
          "Video record or storage resource was not found.",
      });
    }

    return res.status(500).json({
      success: false,
      error:
        error instanceof Error
          ? error.message
          : "Failed to generate video URL.",
    });
  }
}